In [34]:
from tensorflow.keras.preprocessing.text import one_hot # type: ignore

In [35]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [36]:
## Define the vocabulary size
voc_size=10000


In [37]:
### one hot representation 

one_hot_repr= [one_hot(words, voc_size)for words in sent]
one_hot_repr

## indexs

[[1893, 4046, 5937, 9336],
 [1893, 4046, 5937, 5698],
 [1893, 8896, 5937, 1391],
 [9039, 9172, 1618, 5715, 4914],
 [9039, 9172, 1618, 5715, 8611],
 [8908, 1893, 3608, 5937, 6773],
 [9858, 684, 5681, 5715]]

In [48]:
from tensorflow.keras.layers import Embedding # type: ignore

from tensorflow.keras.utils import pad_sequences # type: ignore
from tensorflow.keras.models import Sequential # type: ignore

In [39]:
import numpy as np


In [40]:
## making all sentence of same length 8 , as max is 8 and addding 0 as padding 

sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1893 4046 5937 9336]
 [   0    0    0    0 1893 4046 5937 5698]
 [   0    0    0    0 1893 8896 5937 1391]
 [   0    0    0 9039 9172 1618 5715 4914]
 [   0    0    0 9039 9172 1618 5715 8611]
 [   0    0    0 8908 1893 3608 5937 6773]
 [   0    0    0    0 9858  684 5681 5715]]


In [41]:
## feature representation

## dimensions 300 or 10 for ex

dim=10

In [23]:
## making the model 

model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

# optimizer adam , loss fun mse

c:\Desktop\PYTHON\SRNN Proj02\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [42]:
model.summary()


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [43]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step


array([[[-1.9466484e-02,  9.9923722e-03,  3.9415732e-03, -4.5999911e-02,
          6.6075437e-03, -4.2726554e-02,  3.2367434e-02, -2.5481954e-03,
         -4.7908008e-02, -1.8897211e-02],
        [-1.9466484e-02,  9.9923722e-03,  3.9415732e-03, -4.5999911e-02,
          6.6075437e-03, -4.2726554e-02,  3.2367434e-02, -2.5481954e-03,
         -4.7908008e-02, -1.8897211e-02],
        [-1.9466484e-02,  9.9923722e-03,  3.9415732e-03, -4.5999911e-02,
          6.6075437e-03, -4.2726554e-02,  3.2367434e-02, -2.5481954e-03,
         -4.7908008e-02, -1.8897211e-02],
        [-1.9466484e-02,  9.9923722e-03,  3.9415732e-03, -4.5999911e-02,
          6.6075437e-03, -4.2726554e-02,  3.2367434e-02, -2.5481954e-03,
         -4.7908008e-02, -1.8897211e-02],
        [ 4.5561306e-03, -2.6697053e-02,  4.2385045e-02,  4.4472218e-03,
         -4.6195652e-02, -3.6000408e-02, -3.6595024e-02,  8.0755837e-03,
          3.2180879e-02,  3.5915438e-02],
        [-1.2780167e-02,  1.9582618e-02, -3.2748260e-02,  2.

In [50]:
embedded_docs[0]




array([   0,    0,    0,    0, 1893, 4046, 5937, 9336])

In [52]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step


array([[[-1.9466484e-02,  9.9923722e-03,  3.9415732e-03, -4.5999911e-02,
          6.6075437e-03, -4.2726554e-02,  3.2367434e-02, -2.5481954e-03,
         -4.7908008e-02, -1.8897211e-02],
        [-1.9466484e-02,  9.9923722e-03,  3.9415732e-03, -4.5999911e-02,
          6.6075437e-03, -4.2726554e-02,  3.2367434e-02, -2.5481954e-03,
         -4.7908008e-02, -1.8897211e-02],
        [-1.9466484e-02,  9.9923722e-03,  3.9415732e-03, -4.5999911e-02,
          6.6075437e-03, -4.2726554e-02,  3.2367434e-02, -2.5481954e-03,
         -4.7908008e-02, -1.8897211e-02],
        [-1.9466484e-02,  9.9923722e-03,  3.9415732e-03, -4.5999911e-02,
          6.6075437e-03, -4.2726554e-02,  3.2367434e-02, -2.5481954e-03,
         -4.7908008e-02, -1.8897211e-02],
        [ 4.5561306e-03, -2.6697053e-02,  4.2385045e-02,  4.4472218e-03,
         -4.6195652e-02, -3.6000408e-02, -3.6595024e-02,  8.0755837e-03,
          3.2180879e-02,  3.5915438e-02],
        [-1.2780167e-02,  1.9582618e-02, -3.2748260e-02,  2.